# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.5
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: 58363638+A-Maugli@users.noreply.github.com
author_name: A-Maugli
contract_name: HelloWorld
preset_name: starter
project_name: ex

